all: true
dir: "{{.InterfaceDir}}"
filename: "mock_{{.InterfaceName}}.go"
pkgname: "{{.SrcPackageName}}"
template: testify
template-data:
   unroll-variadic: true
packages:
   github.com/adampresley/adamgokit/rest:
      config:
         all: true
         recursive: true
   github.com/adampresley/adamgokit/httphelpers:
      config:
         all: true
         recursive: true
