// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package sse

import (
	"net/http"

	mock "github.com/stretchr/testify/mock"
)

// NewMockBroker creates a new instance of MockBroker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBroker(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBroker {
	mock := &MockBroker{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockBroker is an autogenerated mock type for the Broker type
type MockBroker struct {
	mock.Mock
}

type MockBroker_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBroker) EXPECT() *MockBroker_Expecter {
	return &MockBroker_Expecter{mock: &_m.Mock}
}

// Listen provides a mock function for the type MockBroker
func (_mock *MockBroker) Listen() {
	_mock.Called()
	return
}

// MockBroker_Listen_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Listen'
type MockBroker_Listen_Call struct {
	*mock.Call
}

// Listen is a helper method to define mock.On call
func (_e *MockBroker_Expecter) Listen() *MockBroker_Listen_Call {
	return &MockBroker_Listen_Call{Call: _e.mock.On("Listen")}
}

func (_c *MockBroker_Listen_Call) Run(run func()) *MockBroker_Listen_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockBroker_Listen_Call) Return() *MockBroker_Listen_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockBroker_Listen_Call) RunAndReturn(run func()) *MockBroker_Listen_Call {
	_c.Run(run)
	return _c
}

// Publish provides a mock function for the type MockBroker
func (_mock *MockBroker) Publish(event Event) {
	_mock.Called(event)
	return
}

// MockBroker_Publish_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Publish'
type MockBroker_Publish_Call struct {
	*mock.Call
}

// Publish is a helper method to define mock.On call
//   - event Event
func (_e *MockBroker_Expecter) Publish(event interface{}) *MockBroker_Publish_Call {
	return &MockBroker_Publish_Call{Call: _e.mock.On("Publish", event)}
}

func (_c *MockBroker_Publish_Call) Run(run func(event Event)) *MockBroker_Publish_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 Event
		if args[0] != nil {
			arg0 = args[0].(Event)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockBroker_Publish_Call) Return() *MockBroker_Publish_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockBroker_Publish_Call) RunAndReturn(run func(event Event)) *MockBroker_Publish_Call {
	_c.Run(run)
	return _c
}

// ServeHTTP provides a mock function for the type MockBroker
func (_mock *MockBroker) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	_mock.Called(w, r)
	return
}

// MockBroker_ServeHTTP_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ServeHTTP'
type MockBroker_ServeHTTP_Call struct {
	*mock.Call
}

// ServeHTTP is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
func (_e *MockBroker_Expecter) ServeHTTP(w interface{}, r interface{}) *MockBroker_ServeHTTP_Call {
	return &MockBroker_ServeHTTP_Call{Call: _e.mock.On("ServeHTTP", w, r)}
}

func (_c *MockBroker_ServeHTTP_Call) Run(run func(w http.ResponseWriter, r *http.Request)) *MockBroker_ServeHTTP_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 http.ResponseWriter
		if args[0] != nil {
			arg0 = args[0].(http.ResponseWriter)
		}
		var arg1 *http.Request
		if args[1] != nil {
			arg1 = args[1].(*http.Request)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBroker_ServeHTTP_Call) Return() *MockBroker_ServeHTTP_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockBroker_ServeHTTP_Call) RunAndReturn(run func(w http.ResponseWriter, r *http.Request)) *MockBroker_ServeHTTP_Call {
	_c.Run(run)
	return _c
}
