// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package s3

import (
	"io"

	"github.com/adampresley/adamgokit/s3/createbucketoptions"
	"github.com/adampresley/adamgokit/s3/deleteoptions"
	"github.com/adampresley/adamgokit/s3/getoptions"
	"github.com/adampresley/adamgokit/s3/geturloptions"
	"github.com/adampresley/adamgokit/s3/listoptions"
	"github.com/adampresley/adamgokit/s3/putoptions"
	mock "github.com/stretchr/testify/mock"
)

// NewMockS3Client creates a new instance of MockS3Client. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockS3Client(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockS3Client {
	mock := &MockS3Client{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockS3Client is an autogenerated mock type for the S3Client type
type MockS3Client struct {
	mock.Mock
}

type MockS3Client_Expecter struct {
	mock *mock.Mock
}

func (_m *MockS3Client) EXPECT() *MockS3Client_Expecter {
	return &MockS3Client_Expecter{mock: &_m.Mock}
}

// BucketExists provides a mock function for the type MockS3Client
func (_mock *MockS3Client) BucketExists(bucket string) (bool, error) {
	ret := _mock.Called(bucket)

	if len(ret) == 0 {
		panic("no return value specified for BucketExists")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (bool, error)); ok {
		return returnFunc(bucket)
	}
	if returnFunc, ok := ret.Get(0).(func(string) bool); ok {
		r0 = returnFunc(bucket)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(bucket)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockS3Client_BucketExists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BucketExists'
type MockS3Client_BucketExists_Call struct {
	*mock.Call
}

// BucketExists is a helper method to define mock.On call
//   - bucket string
func (_e *MockS3Client_Expecter) BucketExists(bucket interface{}) *MockS3Client_BucketExists_Call {
	return &MockS3Client_BucketExists_Call{Call: _e.mock.On("BucketExists", bucket)}
}

func (_c *MockS3Client_BucketExists_Call) Run(run func(bucket string)) *MockS3Client_BucketExists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockS3Client_BucketExists_Call) Return(b bool, err error) *MockS3Client_BucketExists_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockS3Client_BucketExists_Call) RunAndReturn(run func(bucket string) (bool, error)) *MockS3Client_BucketExists_Call {
	_c.Call.Return(run)
	return _c
}

// CreateBucket provides a mock function for the type MockS3Client
func (_mock *MockS3Client) CreateBucket(bucket string, options ...createbucketoptions.CreateBucketOption) error {
	// createbucketoptions.CreateBucketOption
	_va := make([]interface{}, len(options))
	for _i := range options {
		_va[_i] = options[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, bucket)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for CreateBucket")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, ...createbucketoptions.CreateBucketOption) error); ok {
		r0 = returnFunc(bucket, options...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockS3Client_CreateBucket_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateBucket'
type MockS3Client_CreateBucket_Call struct {
	*mock.Call
}

// CreateBucket is a helper method to define mock.On call
//   - bucket string
//   - options ...createbucketoptions.CreateBucketOption
func (_e *MockS3Client_Expecter) CreateBucket(bucket interface{}, options ...interface{}) *MockS3Client_CreateBucket_Call {
	return &MockS3Client_CreateBucket_Call{Call: _e.mock.On("CreateBucket",
		append([]interface{}{bucket}, options...)...)}
}

func (_c *MockS3Client_CreateBucket_Call) Run(run func(bucket string, options ...createbucketoptions.CreateBucketOption)) *MockS3Client_CreateBucket_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []createbucketoptions.CreateBucketOption
		variadicArgs := make([]createbucketoptions.CreateBucketOption, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(createbucketoptions.CreateBucketOption)
			}
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockS3Client_CreateBucket_Call) Return(err error) *MockS3Client_CreateBucket_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockS3Client_CreateBucket_Call) RunAndReturn(run func(bucket string, options ...createbucketoptions.CreateBucketOption) error) *MockS3Client_CreateBucket_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockS3Client
func (_mock *MockS3Client) Delete(bucket string, keys []string, options ...deleteoptions.DeleteOption) (DeleteResponse, error) {
	// deleteoptions.DeleteOption
	_va := make([]interface{}, len(options))
	for _i := range options {
		_va[_i] = options[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, bucket, keys)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 DeleteResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, []string, ...deleteoptions.DeleteOption) (DeleteResponse, error)); ok {
		return returnFunc(bucket, keys, options...)
	}
	if returnFunc, ok := ret.Get(0).(func(string, []string, ...deleteoptions.DeleteOption) DeleteResponse); ok {
		r0 = returnFunc(bucket, keys, options...)
	} else {
		r0 = ret.Get(0).(DeleteResponse)
	}
	if returnFunc, ok := ret.Get(1).(func(string, []string, ...deleteoptions.DeleteOption) error); ok {
		r1 = returnFunc(bucket, keys, options...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockS3Client_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockS3Client_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - bucket string
//   - keys []string
//   - options ...deleteoptions.DeleteOption
func (_e *MockS3Client_Expecter) Delete(bucket interface{}, keys interface{}, options ...interface{}) *MockS3Client_Delete_Call {
	return &MockS3Client_Delete_Call{Call: _e.mock.On("Delete",
		append([]interface{}{bucket, keys}, options...)...)}
}

func (_c *MockS3Client_Delete_Call) Run(run func(bucket string, keys []string, options ...deleteoptions.DeleteOption)) *MockS3Client_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []string
		if args[1] != nil {
			arg1 = args[1].([]string)
		}
		var arg2 []deleteoptions.DeleteOption
		variadicArgs := make([]deleteoptions.DeleteOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(deleteoptions.DeleteOption)
			}
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockS3Client_Delete_Call) Return(deleteResponse DeleteResponse, err error) *MockS3Client_Delete_Call {
	_c.Call.Return(deleteResponse, err)
	return _c
}

func (_c *MockS3Client_Delete_Call) RunAndReturn(run func(bucket string, keys []string, options ...deleteoptions.DeleteOption) (DeleteResponse, error)) *MockS3Client_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockS3Client
func (_mock *MockS3Client) Get(bucket string, key string, options ...getoptions.GetOption) (GetObjectResponse, error) {
	// getoptions.GetOption
	_va := make([]interface{}, len(options))
	for _i := range options {
		_va[_i] = options[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, bucket, key)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 GetObjectResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string, ...getoptions.GetOption) (GetObjectResponse, error)); ok {
		return returnFunc(bucket, key, options...)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string, ...getoptions.GetOption) GetObjectResponse); ok {
		r0 = returnFunc(bucket, key, options...)
	} else {
		r0 = ret.Get(0).(GetObjectResponse)
	}
	if returnFunc, ok := ret.Get(1).(func(string, string, ...getoptions.GetOption) error); ok {
		r1 = returnFunc(bucket, key, options...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockS3Client_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockS3Client_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - bucket string
//   - key string
//   - options ...getoptions.GetOption
func (_e *MockS3Client_Expecter) Get(bucket interface{}, key interface{}, options ...interface{}) *MockS3Client_Get_Call {
	return &MockS3Client_Get_Call{Call: _e.mock.On("Get",
		append([]interface{}{bucket, key}, options...)...)}
}

func (_c *MockS3Client_Get_Call) Run(run func(bucket string, key string, options ...getoptions.GetOption)) *MockS3Client_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []getoptions.GetOption
		variadicArgs := make([]getoptions.GetOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(getoptions.GetOption)
			}
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockS3Client_Get_Call) Return(getObjectResponse GetObjectResponse, err error) *MockS3Client_Get_Call {
	_c.Call.Return(getObjectResponse, err)
	return _c
}

func (_c *MockS3Client_Get_Call) RunAndReturn(run func(bucket string, key string, options ...getoptions.GetOption) (GetObjectResponse, error)) *MockS3Client_Get_Call {
	_c.Call.Return(run)
	return _c
}

// GetUrl provides a mock function for the type MockS3Client
func (_mock *MockS3Client) GetUrl(bucket string, key string, options ...geturloptions.GetUrlOption) (string, error) {
	// geturloptions.GetUrlOption
	_va := make([]interface{}, len(options))
	for _i := range options {
		_va[_i] = options[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, bucket, key)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetUrl")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string, ...geturloptions.GetUrlOption) (string, error)); ok {
		return returnFunc(bucket, key, options...)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string, ...geturloptions.GetUrlOption) string); ok {
		r0 = returnFunc(bucket, key, options...)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string, string, ...geturloptions.GetUrlOption) error); ok {
		r1 = returnFunc(bucket, key, options...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockS3Client_GetUrl_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUrl'
type MockS3Client_GetUrl_Call struct {
	*mock.Call
}

// GetUrl is a helper method to define mock.On call
//   - bucket string
//   - key string
//   - options ...geturloptions.GetUrlOption
func (_e *MockS3Client_Expecter) GetUrl(bucket interface{}, key interface{}, options ...interface{}) *MockS3Client_GetUrl_Call {
	return &MockS3Client_GetUrl_Call{Call: _e.mock.On("GetUrl",
		append([]interface{}{bucket, key}, options...)...)}
}

func (_c *MockS3Client_GetUrl_Call) Run(run func(bucket string, key string, options ...geturloptions.GetUrlOption)) *MockS3Client_GetUrl_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []geturloptions.GetUrlOption
		variadicArgs := make([]geturloptions.GetUrlOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(geturloptions.GetUrlOption)
			}
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockS3Client_GetUrl_Call) Return(s string, err error) *MockS3Client_GetUrl_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockS3Client_GetUrl_Call) RunAndReturn(run func(bucket string, key string, options ...geturloptions.GetUrlOption) (string, error)) *MockS3Client_GetUrl_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockS3Client
func (_mock *MockS3Client) List(bucket string, path string, options ...listoptions.ListOption) (ListResponse, error) {
	// listoptions.ListOption
	_va := make([]interface{}, len(options))
	for _i := range options {
		_va[_i] = options[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, bucket, path)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 ListResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string, ...listoptions.ListOption) (ListResponse, error)); ok {
		return returnFunc(bucket, path, options...)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string, ...listoptions.ListOption) ListResponse); ok {
		r0 = returnFunc(bucket, path, options...)
	} else {
		r0 = ret.Get(0).(ListResponse)
	}
	if returnFunc, ok := ret.Get(1).(func(string, string, ...listoptions.ListOption) error); ok {
		r1 = returnFunc(bucket, path, options...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockS3Client_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockS3Client_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - bucket string
//   - path string
//   - options ...listoptions.ListOption
func (_e *MockS3Client_Expecter) List(bucket interface{}, path interface{}, options ...interface{}) *MockS3Client_List_Call {
	return &MockS3Client_List_Call{Call: _e.mock.On("List",
		append([]interface{}{bucket, path}, options...)...)}
}

func (_c *MockS3Client_List_Call) Run(run func(bucket string, path string, options ...listoptions.ListOption)) *MockS3Client_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []listoptions.ListOption
		variadicArgs := make([]listoptions.ListOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(listoptions.ListOption)
			}
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockS3Client_List_Call) Return(listResponse ListResponse, err error) *MockS3Client_List_Call {
	_c.Call.Return(listResponse, err)
	return _c
}

func (_c *MockS3Client_List_Call) RunAndReturn(run func(bucket string, path string, options ...listoptions.ListOption) (ListResponse, error)) *MockS3Client_List_Call {
	_c.Call.Return(run)
	return _c
}

// Put provides a mock function for the type MockS3Client
func (_mock *MockS3Client) Put(bucket string, key string, body io.Reader, options ...putoptions.PutOption) (PutObjectResponse, error) {
	// putoptions.PutOption
	_va := make([]interface{}, len(options))
	for _i := range options {
		_va[_i] = options[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, bucket, key, body)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Put")
	}

	var r0 PutObjectResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string, io.Reader, ...putoptions.PutOption) (PutObjectResponse, error)); ok {
		return returnFunc(bucket, key, body, options...)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string, io.Reader, ...putoptions.PutOption) PutObjectResponse); ok {
		r0 = returnFunc(bucket, key, body, options...)
	} else {
		r0 = ret.Get(0).(PutObjectResponse)
	}
	if returnFunc, ok := ret.Get(1).(func(string, string, io.Reader, ...putoptions.PutOption) error); ok {
		r1 = returnFunc(bucket, key, body, options...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockS3Client_Put_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Put'
type MockS3Client_Put_Call struct {
	*mock.Call
}

// Put is a helper method to define mock.On call
//   - bucket string
//   - key string
//   - body io.Reader
//   - options ...putoptions.PutOption
func (_e *MockS3Client_Expecter) Put(bucket interface{}, key interface{}, body interface{}, options ...interface{}) *MockS3Client_Put_Call {
	return &MockS3Client_Put_Call{Call: _e.mock.On("Put",
		append([]interface{}{bucket, key, body}, options...)...)}
}

func (_c *MockS3Client_Put_Call) Run(run func(bucket string, key string, body io.Reader, options ...putoptions.PutOption)) *MockS3Client_Put_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 io.Reader
		if args[2] != nil {
			arg2 = args[2].(io.Reader)
		}
		var arg3 []putoptions.PutOption
		variadicArgs := make([]putoptions.PutOption, len(args)-3)
		for i, a := range args[3:] {
			if a != nil {
				variadicArgs[i] = a.(putoptions.PutOption)
			}
		}
		arg3 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3...,
		)
	})
	return _c
}

func (_c *MockS3Client_Put_Call) Return(putObjectResponse PutObjectResponse, err error) *MockS3Client_Put_Call {
	_c.Call.Return(putObjectResponse, err)
	return _c
}

func (_c *MockS3Client_Put_Call) RunAndReturn(run func(bucket string, key string, body io.Reader, options ...putoptions.PutOption) (PutObjectResponse, error)) *MockS3Client_Put_Call {
	_c.Call.Return(run)
	return _c
}

// PutStream provides a mock function for the type MockS3Client
func (_mock *MockS3Client) PutStream(bucket string, key string, options ...putoptions.PutOption) (PutStreamResponse, error) {
	// putoptions.PutOption
	_va := make([]interface{}, len(options))
	for _i := range options {
		_va[_i] = options[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, bucket, key)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for PutStream")
	}

	var r0 PutStreamResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string, ...putoptions.PutOption) (PutStreamResponse, error)); ok {
		return returnFunc(bucket, key, options...)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string, ...putoptions.PutOption) PutStreamResponse); ok {
		r0 = returnFunc(bucket, key, options...)
	} else {
		r0 = ret.Get(0).(PutStreamResponse)
	}
	if returnFunc, ok := ret.Get(1).(func(string, string, ...putoptions.PutOption) error); ok {
		r1 = returnFunc(bucket, key, options...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockS3Client_PutStream_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PutStream'
type MockS3Client_PutStream_Call struct {
	*mock.Call
}

// PutStream is a helper method to define mock.On call
//   - bucket string
//   - key string
//   - options ...putoptions.PutOption
func (_e *MockS3Client_Expecter) PutStream(bucket interface{}, key interface{}, options ...interface{}) *MockS3Client_PutStream_Call {
	return &MockS3Client_PutStream_Call{Call: _e.mock.On("PutStream",
		append([]interface{}{bucket, key}, options...)...)}
}

func (_c *MockS3Client_PutStream_Call) Run(run func(bucket string, key string, options ...putoptions.PutOption)) *MockS3Client_PutStream_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []putoptions.PutOption
		variadicArgs := make([]putoptions.PutOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(putoptions.PutOption)
			}
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockS3Client_PutStream_Call) Return(putStreamResponse PutStreamResponse, err error) *MockS3Client_PutStream_Call {
	_c.Call.Return(putStreamResponse, err)
	return _c
}

func (_c *MockS3Client_PutStream_Call) RunAndReturn(run func(bucket string, key string, options ...putoptions.PutOption) (PutStreamResponse, error)) *MockS3Client_PutStream_Call {
	_c.Call.Return(run)
	return _c
}

// StatObject provides a mock function for the type MockS3Client
func (_mock *MockS3Client) StatObject(bucket string, key string) (*ObjectMetadata, error) {
	ret := _mock.Called(bucket, key)

	if len(ret) == 0 {
		panic("no return value specified for StatObject")
	}

	var r0 *ObjectMetadata
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string) (*ObjectMetadata, error)); ok {
		return returnFunc(bucket, key)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string) *ObjectMetadata); ok {
		r0 = returnFunc(bucket, key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ObjectMetadata)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = returnFunc(bucket, key)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockS3Client_StatObject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StatObject'
type MockS3Client_StatObject_Call struct {
	*mock.Call
}

// StatObject is a helper method to define mock.On call
//   - bucket string
//   - key string
func (_e *MockS3Client_Expecter) StatObject(bucket interface{}, key interface{}) *MockS3Client_StatObject_Call {
	return &MockS3Client_StatObject_Call{Call: _e.mock.On("StatObject", bucket, key)}
}

func (_c *MockS3Client_StatObject_Call) Run(run func(bucket string, key string)) *MockS3Client_StatObject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockS3Client_StatObject_Call) Return(objectMetadata *ObjectMetadata, err error) *MockS3Client_StatObject_Call {
	_c.Call.Return(objectMetadata, err)
	return _c
}

func (_c *MockS3Client_StatObject_Call) RunAndReturn(run func(bucket string, key string) (*ObjectMetadata, error)) *MockS3Client_StatObject_Call {
	_c.Call.Return(run)
	return _c
}
