// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package awsconfig

import (
	"github.com/aws/aws-sdk-go-v2/config"
	mock "github.com/stretchr/testify/mock"
)

// NewMockConfiger creates a new instance of MockConfiger. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockConfiger(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockConfiger {
	mock := &MockConfiger{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockConfiger is an autogenerated mock type for the Configer type
type MockConfiger struct {
	mock.Mock
}

type MockConfiger_Expecter struct {
	mock *mock.Mock
}

func (_m *MockConfiger) EXPECT() *MockConfiger_Expecter {
	return &MockConfiger_Expecter{mock: &_m.Mock}
}

// GetConfigValues provides a mock function for the type MockConfiger
func (_mock *MockConfiger) GetConfigValues() config.Config {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetConfigValues")
	}

	var r0 config.Config
	if returnFunc, ok := ret.Get(0).(func() config.Config); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(config.Config)
		}
	}
	return r0
}

// MockConfiger_GetConfigValues_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetConfigValues'
type MockConfiger_GetConfigValues_Call struct {
	*mock.Call
}

// GetConfigValues is a helper method to define mock.On call
func (_e *MockConfiger_Expecter) GetConfigValues() *MockConfiger_GetConfigValues_Call {
	return &MockConfiger_GetConfigValues_Call{Call: _e.mock.On("GetConfigValues")}
}

func (_c *MockConfiger_GetConfigValues_Call) Run(run func()) *MockConfiger_GetConfigValues_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockConfiger_GetConfigValues_Call) Return(config1 config.Config) *MockConfiger_GetConfigValues_Call {
	_c.Call.Return(config1)
	return _c
}

func (_c *MockConfiger_GetConfigValues_Call) RunAndReturn(run func() config.Config) *MockConfiger_GetConfigValues_Call {
	_c.Call.Return(run)
	return _c
}

// Load provides a mock function for the type MockConfiger
func (_mock *MockConfiger) Load() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Load")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockConfiger_Load_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Load'
type MockConfiger_Load_Call struct {
	*mock.Call
}

// Load is a helper method to define mock.On call
func (_e *MockConfiger_Expecter) Load() *MockConfiger_Load_Call {
	return &MockConfiger_Load_Call{Call: _e.mock.On("Load")}
}

func (_c *MockConfiger_Load_Call) Run(run func()) *MockConfiger_Load_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockConfiger_Load_Call) Return(err error) *MockConfiger_Load_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockConfiger_Load_Call) RunAndReturn(run func() error) *MockConfiger_Load_Call {
	_c.Call.Return(run)
	return _c
}
