// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package httphelpers

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockRequestTypes creates a new instance of MockRequestTypes. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRequestTypes(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRequestTypes {
	mock := &MockRequestTypes{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRequestTypes is an autogenerated mock type for the RequestTypes type
type MockRequestTypes struct {
	mock.Mock
}

type MockRequestTypes_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRequestTypes) EXPECT() *MockRequestTypes_Expecter {
	return &MockRequestTypes_Expecter{mock: &_m.Mock}
}
